# Generated by Django 5.2.17 on 2026-09-26 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_text', models.CharField(default='Who We Are', max_length=120)),
                ('heading_line1', models.CharField(default='Engineering Minds Behind', max_length=150)),
                ('heading_highlight', models.CharField(default='Tecnsol', max_length=150)),
                ('description', models.TextField(default="We're a tight-knit collective of engineers, designers and strategists obsessed with building fast, beautiful, future-proof digital products. Every pixel and every line of code is written with intent.")),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('years_experience', models.PositiveIntegerField(default=8)),
                ('team_members_count', models.PositiveIntegerField(default=12)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Section',
            },
        ),
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Main Campus, Computer Lab, Punjab Institute of Technology', max_length=120)),
                ('logo', models.ImageField(help_text='The institute/campus photo shown in the slider.', upload_to='collaborations/')),
                ('quote', models.TextField(blank=True, default='', help_text='Optional short testimonial/quote shown under this photo in the slider.')),
                ('quote_author', models.CharField(blank=True, default='', help_text="Optional. Who said the quote, e.g. 'Dr. Ahmed, Director'. Leave blank to just show the Name above as the caption.", max_length=120)),
                ('website_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Institute Photo / Quote',
                'verbose_name_plural': 'Institute Photos / Quotes',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='fa-solid fa-code', help_text='Font Awesome icon class, e.g. fa-solid fa-code', max_length=60)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('proficiency_pct', models.PositiveSmallIntegerField(default=90, help_text='0-100, drives the animated skill bar')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Expertise',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('category', models.CharField(choices=[('web_development', 'Web Development'), ('graphics', 'Graphics Design')], default='web_development', max_length=30)),
                ('tagline', models.CharField(blank=True, help_text='Small badge label shown on the image, e.g. FinTech SaaS', max_length=120)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('tags', models.CharField(blank=True, help_text='Comma separated, e.g. React, Tailwind, ChartJS', max_length=255)),
                ('live_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show this project in the homepage carousel')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='fa-solid fa-code', help_text='Font Awesome icon class, e.g. fa-solid fa-code', max_length=60)),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField()),
                ('tags', models.CharField(blank=True, help_text='Comma separated, e.g. ReactJS, TailwindCSS, TypeScript', max_length=255)),
                ('image', models.ImageField(blank=True, help_text="Optional. Shown as the banner image on this service's detail page. Leave blank to show an animated icon placeholder instead.", null=True, upload_to='services/')),
                ('fee', models.CharField(blank=True, help_text='Shown on the service detail page, e.g. $499, $299/mo, Free Consultation', max_length=60)),
                ('duration', models.CharField(blank=True, help_text='Shown on the service detail page, e.g. 4 Weeks, 2 Months, Ongoing', max_length=60)),
                ('detail_description', models.TextField(blank=True, help_text="Optional. Longer write-up shown only on the service's detail page. Leave blank to reuse the short description above.")),
                ('outline_pdf', models.FileField(blank=True, help_text="Optional. Upload a course outline PDF here to show a Download button on this service's page. Visitors fill Name/Phone/Email before it downloads. Leave blank to hide the Download button.", null=True, upload_to='service_outlines/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_badge_text', models.CharField(default='Architecting Next-Gen Web Solutions', max_length=120)),
                ('hero_heading_line1', models.CharField(default='We Engineer', max_length=150)),
                ('hero_heading_highlight', models.CharField(default='Digital Brilliance', max_length=150)),
                ('hero_heading_line2', models.CharField(default='With Code', max_length=150)),
                ('hero_subtitle', models.TextField(default='Tecnsol empowers brands with hyper-scalable web architectures, bespoke frontend design engineering, and modern digital ecosystems optimized for unmatched speed and performance.')),
                ('stat_projects_delivered', models.PositiveIntegerField(default=180)),
                ('stat_satisfied_clients_pct', models.DecimalField(decimal_places=1, default=99, max_digits=5)),
                ('stat_code_commits_k', models.PositiveIntegerField(default=240)),
                ('stat_uptime_pct', models.DecimalField(decimal_places=1, default=99.9, max_digits=5)),
                ('contact_email', models.EmailField(default='contact@tecnsol.io', max_length=254)),
                ('contact_phone', models.CharField(default='+1 (800) 832-6765', max_length=50)),
                ('contact_location', models.CharField(default='Silicon Valley & Global Remote', max_length=150)),
                ('contact_intro', models.TextField(default='Ready to elevate your web presence or launch a high-performance web application? Fill out the project inquiry form, and our tech lead will respond within 12 hours.')),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('discord_url', models.URLField(blank=True)),
                ('map_embed_url', models.URLField(blank=True, help_text='Optional. Paste a Google Maps embed URL (Maps → Share → Embed a map → copy the src="..." link) to pin an exact location on the Contact page. Leave blank to auto-generate a map from the Location field above.')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(help_text='e.g. Lead Frontend Engineer', max_length=120)),
                ('photo', models.ImageField(upload_to='team/')),
                ('bio', models.CharField(blank=True, max_length=200)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TechStackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('icon_class', models.CharField(help_text='Font Awesome icon class, e.g. fa-brands fa-react', max_length=60)),
                ('icon_color', models.CharField(default='text-maroon-glow', help_text='Tailwind text color utility class, e.g. text-cyan-400', max_length=40)),
                ('category_label', models.CharField(help_text='Small label under the name, e.g. Frontend, Database', max_length=60)),
                ('website_url', models.URLField(blank=True, help_text='Optional. If set, clicking this tech card opens this link in a new tab.')),
                ('icon_image_url', models.URLField(blank=True, help_text='Optional. Direct image/SVG URL for the logo — use this when Font Awesome has no icon for the tool (e.g. Adobe apps). Overrides the Font Awesome icon class above when set.')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tech Stack Item',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(help_text='e.g. CTO, Nexus Technologies', max_length=150)),
                ('avatar', models.ImageField(upload_to='testimonials/')),
                ('review', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DownloadLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(blank=True, help_text='Which service/course outline this person downloaded.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloads', to='core.service')),
            ],
            options={
                'verbose_name': 'Outline Download Lead',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('budget', models.CharField(choices=[('2500-5000', '$2,500 - $5,000'), ('5000-10000', '$5,000 - $10,000'), ('10000+', '$10,000+')], max_length=30)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('service_needed', models.ForeignKey(blank=True, help_text='Which service/course this inquiry is about. Auto-filled when someone clicks "Apply Now" on a service\'s detail page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='core.service')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'ordering': ['-created_at'],
            },
        ),
    ]
