# Generated by Django 5.0.6 on 2026-09-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('logo', models.ImageField(help_text='The partner/brand logo — works best as a transparent PNG.', upload_to='partners/')),
                ('website_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Partner Logo',
                'verbose_name_plural': 'Partner Logos',
                'ordering': ['order', 'id'],
            },
        ),
    ]
