# Generated by Django 5.0.6 on 2026-09-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_facebook_url_sitesettings_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='portfolio_url',
            field=models.URLField(blank=True, help_text='Personal website / portfolio link'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
